// flow-typed signature: 57b4fd5f7f9bd4a27338e5dcee033ba8
// flow-typed version: <<STUB>>/react-navigation-is-focused-hoc_v^1.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-is-focused-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-is-focused-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-navigation-is-focused-hoc/index' {
  declare module.exports: $Exports<'react-navigation-is-focused-hoc'>;
}
declare module 'react-navigation-is-focused-hoc/index.js' {
  declare module.exports: $Exports<'react-navigation-is-focused-hoc'>;
}
